In [1]:
import numpy as np

In [2]:
two=np.array([[1,2,3],[4,5,6]])

In [3]:
two

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.where(two>3)

(array([1, 1, 1]), array([0, 1, 2]))

In [8]:
two1=np.array([[2,4,1],[4,1,2]])

In [9]:
two1

array([[2, 4, 1],
       [4, 1, 2]])

In [10]:
np.where(two1==4)

(array([0, 1]), array([1, 0]))

In [11]:
import pandas as pd

In [12]:
em=pd.Series()

In [13]:
em

Series([], dtype: object)

In [19]:
arr=np.array([1,2,3,4,5])
a=pd.Series(arr)

In [20]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [23]:
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}


In [24]:
dict1

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [27]:
a2=pd.Series(dict1)

In [28]:
a2.size

5

In [30]:
a2.shape

(5,)

In [31]:
a2[0]

1

In [34]:
a2[1:4]

b    2
c    3
d    4
dtype: int64

In [35]:
arr[1:4]

array([2, 3, 4])

In [36]:
arr[-4:]

array([2, 3, 4, 5])

In [38]:
em.empty

True

In [40]:
a2.hasnans

False

In [41]:
a2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [42]:
a2>=4

a    False
b    False
c    False
d     True
e     True
dtype: bool

In [43]:
a2[a2>4]

e    5
dtype: int64

In [44]:
a2.sum()

15

In [59]:
s1=pd.Series([2,5,None,3,1,7,None])

s1

In [51]:
s1.sort_values(ascending=False)

4    7
1    5
2    3
0    2
3    1
dtype: int64

In [53]:
s1

0    2.0
1    5.0
2    3.0
3    1.0
4    7.0
5    NaN
dtype: float64

In [55]:
s1[s1.isnull()]

5   NaN
dtype: float64

In [57]:
s1.fillna(8)

0    2.0
1    5.0
2    3.0
3    1.0
4    7.0
5    8.0
dtype: float64

In [60]:
s1

0    2.0
1    5.0
2    NaN
3    3.0
4    1.0
5    7.0
6    NaN
dtype: float64

In [62]:
s1.dropna()

0    2.0
1    5.0
3    3.0
4    1.0
5    7.0
dtype: float64

In [64]:
s1.value_counts()

2.0    1
5.0    1
3.0    1
1.0    1
7.0    1
Name: count, dtype: int64

In [69]:
s1.loc[2]

nan

In [70]:
s1

0    2.0
1    5.0
2    NaN
3    3.0
4    1.0
5    7.0
6    NaN
dtype: float64

In [73]:
s1.iloc[2:3]

2   NaN
dtype: float64

In [74]:
for i in s1:
    if i==3.0:
        print('found')
        

found


In [78]:
for index,i in enumerate(s1):
     if i==3.0:
        print("index", index,"vale",i)


index 3 vale 3.0


In [79]:
s1

0    2.0
1    5.0
2    NaN
3    3.0
4    1.0
5    7.0
6    NaN
dtype: float64

In [80]:
s1.dropna()

0    2.0
1    5.0
3    3.0
4    1.0
5    7.0
dtype: float64

In [81]:
def multiply(x):
    return 3*x
s1.apply(multiply)

0     6.0
1    15.0
2     NaN
3     9.0
4     3.0
5    21.0
6     NaN
dtype: float64